routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', function () {
    if (auth()->check()) {
        return redirect('/dashboard');
    } else {
        return redirect('/login');
    }
});

Route::get('/home', function () {
    return redirect('/dashboard');
});

/*
   |--------------------------------------------------------------------------
   | Routes Without authentication
   |--------------------------------------------------------------------------
 */
Route::get('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/password/forgot', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password_reset_save');
Route::post('/reset/password', 'Auth\ResetPasswordController@reset')->name('password.reset');


Auth::routes();

Route::group(['middleware' => 'auth'], function () {


    Route::group(['namespace' => 'Auth'], function () {

        Route::get('update-profile', 'ProfileController@editProfile')->name('edit.profile');
        Route::post('update-profile', 'ProfileController@updateProfile')->name('update.profile');

        Route::get('logout', 'LoginController@logout')->name('logout');
    });

    /*
      |--------------------------------------------------------------------------
      | Super Admin Routes
      |--------------------------------------------------------------------------
    */
    Route::group(['namespace' => 'Backend'], function () {

        //After Login redirect to dashboard
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        Route::resource('users', 'UserController');
        Route::get('users/delete/{id}', ['as' => 'users.delete', 'uses' => 'UserController@destroy']);

        Route::resource('roles', 'RoleController');
        Route::get('roles/delete/{id}', ['as' => 'roles.delete', 'uses' => 'RoleController@destroy']);

        //Custom Module
        Route::resource('clients', 'ClientController');
        Route::get('clients/delete/{id}', ['as' => 'clients.delete', 'uses' => 'ClientController@destroy']);

        Route::resource('transactions', 'TransactionController');
        Route::get('transactions/delete/{id}', ['as' => 'transactions.delete', 'uses' => 'TransactionController@destroy']);

        Route::get('client_transactions/index', ['as' => 'client_transactions.index', 'uses' => 'ClientTransactionController@index']);
        Route::get('client_transactions/create/{transaction_id}', ['as' => 'client_transactions.create', 'uses' => 'ClientTransactionController@create']);
        Route::post('client_transactions/create/{transaction_id}', ['as' => 'client_transactions.store', 'uses' => 'ClientTransactionController@store']);
        Route::get('client_transactions/edit/{transaction_id}', ['as' => 'client_transactions.edit', 'uses' => 'ClientTransactionController@edit']);
        Route::put('client_transactions/update/{transaction_id}', ['as' => 'client_transactions.update', 'uses' => 'ClientTransactionController@update']);
       //Route::get('client_transactions/delete/{id}', ['as' => 'transactions.delete', 'uses' => 'ClientTransactionController@destroy']);

        Route::get('interest_cron',['as'=>'interest_cron','uses'=>'TransactionCronController@add_pending_interests']);
    });
});

app/Http/Controllers/Backend/ClientController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Requests\Backend\UserStoreRequest;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\UserUpdateRequest;
use App\Repositories\Backend\User\UserContract;
use App\Role;
use Illuminate\Support\Facades\Log;

class ClientController extends Controller
{
    protected $repository;

    public function __construct(UserContract $repository)
    {
        $this->repository = $repository;
    }

    public function index()
    {
        try {
            $users = $this->repository->getAllClients();
            return view('backend.clients.index', compact('users'));

        } catch (\Exception $e) {
            Log::error('User management error:' . $e->getMessage());
            return redirect()->route('clients.index')->with('failure', 'Something went wrong');
        }
    }

    public function create()
    {
       // $roles = Role::all();
        return view('backend.clients.form');
    }

    public function store(UserStoreRequest $request)
    {
        try {
            $input = $request->only('name', 'email', 'phone');
            $client_role = Role::where('name','client')->first()->id;
            $input['roles'] = [$client_role];
            $user = $this->repository->store($input);
            return redirect()->route('clients.index')->with('success', 'New User added successfully');

        } catch (\Exception $e) {
            Log::error('User management error:' . $e->getMessage() . 'on Line ' . $e->getLine() . '-->' . $e->getFile());
            return redirect()->route('clients.index')->with('failure', 'Something went wrong');
        }
    }

    public function edit($id)
    {
        try {
            $user = $this->repository->find($id);
            return view('backend.clients.form', compact('user'));

        } catch (\Exception $e) {
            Log::error('User management error:' . $e->getMessage());
            return redirect()->route('clients.index')->with('failure', 'Something went wrong');
        }
    }

    public function update(UserUpdateRequest $request, $id)
    {

        try {
            $input = $request->only('name', 'email');
            $this->repository->update($id, $input);
            return redirect()->route('clients.index')->with('success', 'User updated successfully');

        } catch (\Exception $e) {
            Log::error('User management error:' . $e->getMessage() . 'on Line ' . $e->getLine() . '-->' . $e->getFile());
            return redirect()->route('clients.index')->with('Something went wrong');
        }
    }

    public function destroy($id)
    {
        try {
            $this->repository->delete($id);
            return redirect()->route('clients.index')->with('success', 'User deleted successfully');

        } catch (\Exception $e) {
            Log::error('User management error:' . $e->getMessage());
            return redirect()->route('clients.index')->with('failure', 'Something went wrong');
        }
    }
}

app/Http/Controllers/Backend/ClientTransactionController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\ClientTransactionRequest;
use App\Http\Requests\Backend\ClientTransactionUpdateRequest;
use App\models\ClientTransaction;
use App\models\Transaction;
use App\Repositories\Backend\ClientTransaction\ClientTransactionContract;
use App\Repositories\Backend\User\UserContract;
use App\User;
use Illuminate\Support\Facades\Log;

class ClientTransactionController extends Controller
{
    protected $repository;
    protected $user_repository;

    public function __construct(ClientTransactionContract $repository,UserContract $userRepository)
    {
        $this->repository = $repository;
        $this->user_repository = $userRepository;
    }

    public function index()
    {

        try {
            $client_transactions = $this->repository->getAll();

            $client_transaction = $client_transactions->filter(function ($item){

                if(!empty($item->transaction)) {
                    $item->client_name = User::where('id',$item->transaction->user_id)->first()->name;

                }

                return $item->transaction_date = date('d-m-Y',strtotime($item->pending_payment_date));
            });

            return view('backend.client_transactions.index', compact('client_transactions'));

        } catch (\Exception $e) {
            Log::error('Transaction management error:' . $e->getMessage());
            return redirect()->route('transactions.index')->with('failure', 'Something went wrong');
        }
    }

    public function create($transaction_id)
    {

        if(!empty($transaction_id)) {
            $transaction = Transaction::find($transaction_id);
            $pending_interests_amount = 0;
            if($transaction->with_interest == 'Yes') {
                $pending_interests_amount = $this->repository->getPendingInterestByTransaction($transaction_id);
            }

            return view('backend.client_transactions.form', compact('transaction_id','transaction'));
        }
        else {
            return redirect()->route('transactions.index')->with('failure', 'Transaction Not Found');
        }

    }

    public function store(ClientTransactionRequest $request,$transaction_id)
    {
        try {

            $input = $request->only('transaction_id', 'amount', 'payment_mode','payment_type','note','payment_date');
            $input['payment_date'] = date("Y-m-d",strtotime($input['payment_date']));
            $input['pending_payment_date'] = date("Y-m-d",strtotime($input['payment_date']));
            $transaction = Transaction::find($transaction_id);
            if($input['amount'] > $transaction->pending_amount ) {
                return redirect()->route('transactions.show',$transaction_id)->with('failure', 'Payment amount is larger than pending amount');
            }

            //Find Last client date for paid primary amount
            $last_client_transaction = $this->repository->getLastClientTransaction('Primary Amount',$transaction_id);
            if(!empty($last_client_transaction)) {
                $last_client_transaction_date = $last_client_transaction->payment_date;
            }

            $ctransaction = $this->repository->store($input);
            $pending_interests_amount = 0;

            //Update Pending Amount for Parimary Payment
            if( $input['payment_type'] == 'Primary Amount' ) {
                $last_pending_amount = $transaction->pending_amount;
                $transaction->pending_amount = $transaction->pending_amount - $input['amount'];
                $transaction->update();

                //Check and make pending interest entries for last date
               // echo $pending_amount.'<hr>';
               // echo $pending_interests_amount.'<hr>';

                //Check For last Month Interest
                $current_date = $input['payment_date']; //Consider current month date
                $current_month_start = date('Y-m-1',strtotime($input['payment_date']));
                if(empty($last_client_transaction_date)) {

                    $days_count = intval($this->dateDiffInDays($current_date,$current_month_start));
                }
                else if(date('m-Y',strtotime($last_client_transaction_date)) == date('m-Y',strtotime($current_month_start))) {
                    $days_count = intval($this->dateDiffInDays($current_date,$last_client_transaction_date));
                }
                else {
                    $days_count = intval($this->dateDiffInDays($current_date,$current_month_start));
                }

                $interest_amount_month = ($last_pending_amount * $transaction->interest_rate) / 100;
                $interest_amount_days = ($interest_amount_month * $days_count) / 30;
                if(!empty($interest_amount_days)) {

                    $client_transaction = [];
                    $client_transaction['transaction_id'] = $transaction->id;
                    $client_transaction['amount'] = $interest_amount_days;
                    $client_transaction['payment_type'] = 'Interest Amount';
                    $client_transaction['pending_payment_date'] = $current_date;
                    $client_transaction['payment_date'] = $current_date;
                    $client_transaction['payment_status'] = 'Pending';
                    $client_transaction['note'] = 'Pending Interest record auto generated for '.$days_count.' days';
                    $client_trans = $this->repository->store($client_transaction);
            }

           $pending_interests_amount = $this->repository->getPendingInterestByTransaction($transaction_id);


            if($transaction->pending_amount == 0) {

                //Make Completed Transaction
                if($transaction->with_interest == 'No') {
                    echo "12<br>";
                    $transaction->status = 'Completed';
                    $transaction->update();
                }
                else if ($transaction->with_interest == 'Yes') {
                    if($pending_interests_amount == 0 ) {
                        $transaction->status = 'Completed';
                        $transaction->update();
                    }
                 }
                }
            }
            else {
                $pending_interests_amount = $this->repository->getPendingInterestByTransaction($transaction_id);
                if($pending_interests_amount == 0 ) {
                    $transaction->status = 'Completed';
                    $transaction->update();
                }
            }

            return redirect()->route('transactions.show',$transaction_id)->with('success', 'New Client Payment added successfully');

        } catch (\Exception $e) {
            Log::error('Transaction management error:' . $e->getMessage() . 'on Line ' . $e->getLine() . '-->' . $e->getFile());
            return redirect()->route('transactions.index')->with('failure', 'Something went wrong');
        }
    }


    public function edit($id)
    {

        try {
            $client_transactions = $this->repository->find($id);
            $transaction = Transaction::find($client_transactions->transaction_id);
            $pending_interests_amount = $this->repository->getPendingInterestByTransaction($client_transactions->transaction_id);
            return view('backend.client_transactions.form', compact('client_transactions','transaction','pending_interests_amount'));

        } catch (\Exception $e) {
            Log::error('Transaction management error:' . $e->getMessage());
            return redirect()->route('client_transactions.index')->with('failure', 'Something went wrong');
        }
    }

    public function update(ClientTransactionUpdateRequest $request, $id)
    {
        try {
            $input = $request->only('transaction_id',  'payment_mode','payment_type','note','payment_date');
            $input['payment_date'] = date("Y-m-d",strtotime($input['payment_date']));
            $input['payment_status']  = 'Paid';

            $transaction = Transaction::find($input['transaction_id']);
            $this->repository->update($id, $input);
            $pending_interests_amount = $this->repository->getPendingInterestByTransaction($input['transaction_id']);
            if( $pending_interests_amount == 0  && $transaction->pending_amount == 0 ) {
                $transaction->status = 'Completed';
                $transaction->update();
            }
            return redirect()->route('transactions.show',$input['transaction_id'])->with('success', 'Client Transaction updated successfully');

        } catch (\Exception $e) {
            Log::error('Transaction management error:' . $e->getMessage() . 'on Line ' . $e->getLine() . '-->' . $e->getFile());
            return redirect()->route('client_transactions.index')->with('Something went wrong');
        }
    }

    public function destroy($id)
    {
        try {
            $this->repository->delete($id);
            return redirect()->route('client_transactions.index')->with('success', 'Transaction deleted successfully');

        } catch (\Exception $e) {
            Log::error('Transaction management error:' . $e->getMessage());
            return redirect()->route('client_transactions.index')->with('failure', 'Something went wrong');
        }
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\models\ClientTransaction;
use App\models\Transaction;
use App\Repositories\Backend\Dashboard\DashboardContract;
use App\Repositories\Backend\User\UserRepository;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class DashboardController extends Controller
{
    protected $repository;

    public function __construct(DashboardContract $repository)
    {
        $this->repository = $repository;
    }

    //return all the reservation record from database
    public function index()
    {
        try {

            DB::enableQueryLog();
            $day = date("d");
            $transactions = Transaction::with('client')->where('status','Ongoing')
                                        ->get();

            $user_role = 'client';
            $user_count = $users_data = User::whereHas('roles', function($q) use($user_role){
                if(!empty($user_role)) {
                    $q->whereIn('name',[$user_role]);
                }

            })->count();
            return view('backend.dashboard', compact('user_count','transactions'));

        } catch (\Exception $e) {
            Log::error('Dashboard error:' . $e->getMessage());
           // return redirect()->route('dashboard')->with('failure', 'Something went wrong');

        }
    }


}

resources/views/backend/transactions/form.blade.php
@extends('backend.layouts.master')
@section('content')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">
        <div class="m-subheader ">
            <div class="d-flex align-items-center">
                <div class="mr-auto">
                    <h3 class="m-subheader__title">
                        {{(isset($transaction))? 'Edit Transaction' : 'Add Transaction' }}
                    </h3>
                </div>
            </div>
        </div>

        <div class="m-content" style="width: 100%">
            <div class="m-portlet m-portlet--tab">
                <form id="transactionForm" class="m-form m-form--fit m-form--label-align-right"
                      action="{{ isset($transaction) ? route('transactions.update', $transaction->id) : route('transactions.store')}}"
                      method="POST" enctype="multipart/form-data">
                    @csrf
                    @if(isset($transaction))
                        @method('PUT')
                    @endif
                    <div class="m-portlet__body">

                        <div class="form-group row">
                            <div class="col-lg-6">
                                <div class="form-group m-form__group ">
                                    <label class="">
                                        Select Client *
                                    </label>
                                    <select class="form-control m-input m_selectpicker" name="user_id" data-live-search="true">
                                        <option value="" disabled selected>Select Client</option>
                                        @if(isset($clients) &&  count($clients) > 0)
                                            @foreach($clients as $client)
                                                <option
                                                        value="{{ $client->id }}" @if( (isset($transaction) && $transaction->user_id == $client->id ) || old('user_id') == $client->id ) selected @endif>
                                                    {{ $client->name }}
                                                </option>
                                            @endforeach
                                        @endif
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-lg-6">
                                <div class="form-group m-form__group ">
                                    <label class="">
                                        Amount*
                                    </label>
                                    <input type="text" class="form-control m-input" name="amount"
                                           placeholder="Enter Amount"
                                           value="{!! isset($transaction) ? $transaction->amount : old('amount') !!}">
                                </div>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-lg-6">
                                <div class="form-group m-form__group ">
                                    <label class="">
                                        With Interest*
                                    </label>
                                    <div class="m-radio-list">
                                        <label class="m-radio">
                                            <input type="radio" name="with_interest" class="interestOption"  value="Yes" {!! ((isset($transaction) && $transaction->with_interest == 'Yes') || (old('with_interest') == 'Yes'))?'CHECKED' : '' !!}  > Yes
                                            <span></span>
                                        </label>
                                        <label class="m-radio">
                                            <input type="radio" name="with_interest" class="interestOption" value="No" {!! ((isset($transaction) && $transaction->with_interest == 'No') || (!isset($transaction) && old('with_interest') != 'Yes'))?'CHECKED' : '' !!} > No
                                            <span></span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 IneterestDiv" style="{!! ((isset($transaction) && $transaction->with_interest == 'Yes') || old('with_interest') == 'Yes') ?'display: block;' :'display: none;'  !!} ">
                                <div class="form-group m-form__group ">
                                    <label class="">
                                         Interest Rate*
                                    </label>
                                    <input type="text" class="form-control m-input" name="interest_rate"
                                           placeholder="Enter Interest Rate"
                                           value="{!! isset($transaction) ? $transaction->interest_rate : old('interest_rate') !!}">
                                </div>
                            </div>
                        </div>
                        <div class="form-group row IneterestDateDiv" style="{!! ((isset($transaction) && $transaction->with_interest == 'Yes') || old('with_interest') == 'Yes')  ?'display: flex;' :'display: none;'  !!} ">
                           <div class="col-lg-6">
                                <div class="form-group m-form__group ">
                                    <label class="">
                                        Interest Payment Date From* (Day of Month)
                                    </label>

                                    <select name="dom_from" class="form-control m-input col-lg-3">
                                        @foreach(range(1, 30, 1) as $i)
                                            <option  value="{{ $i }}" @if((isset($transaction) && $transaction->dom_from == $i) || old('dom_from') == $i ) selected @endif>{{ $i }}</option>
                                        @endforeach
                                    </select>
                                </div>
                           </div>
                            <div class="col-lg-6">
                               <div class="form-group m-form__group ">
                                   <label class="">
                                       Interest Payment  Date To* (Day of Month)
                                   </label>
                                    <select name="dom_to" class="form-control m-input col-lg-3">
                                        @foreach(range(1, 30, 1) as $i)
                                            <option value="{{ $i }}" @if((isset($transaction) && $transaction->dom_to == $i ) || old('dom_to') == $i ) selected @endif>{{ $i }}</option>
                                        @endforeach
                                    </select>
                                </div>
                           </div>

                        </div>
                        <div class="form-group row">
                            <div class="col-lg-6">
                                <div class="form-group m-form__group ">
                                    <label class="">
                                        Payment Mode*
                                    </label>
                                    <div class="m-radio-list">
                                        <label class="m-radio">
                                            <input type="radio" name="payment_mode" class=""  value="Cash"  {!! ((isset($transaction) && $transaction->payment_mode == 'Cash') || (!isset($transaction) && old('payment_mode') != 'Bank Transfer'))?'CHECKED' : '' !!}> Cash
                                            <span></span>
                                        </label>
                                        <label class="m-radio">
                                            <input type="radio" name="payment_mode" class="" value="Bank Transfer" {!! ((!empty($transaction) && $transaction->payment_mode == 'Bank Transfer') || (!isset($transaction) && old('payment_mode') == 'Bank Transfer') ) ?'CHECKED' : '' !!}> Bank Transfer
                                            <span></span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-lg-6">
                                <div class="form-group m-form__group ">
                                    <label class="">
                                       Transaction Date*
                                    </label>
                                    <input type="text" class="form-control m-input" name="transaction_date" id="m_datepicker_1"
                                           autocomplete="off"  placeholder="{!! (!empty($transaction))? date('m/d/Y',strtotime($transaction->transaction_date)) : '' !!}"
                                           value="{!! (!empty($transaction))? date('m/d/Y',strtotime($transaction->transaction_date)) : old('transaction_date') !!}">
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-lg-6">
                                <div class="form-group m-form__group ">
                                    <label class="">
                                        Note*
                                    </label>
                                    <textarea  class="form-control m-input" name="note" id="" rows="3">{!! (!empty($transaction))?$transaction->note : '' !!}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="m-portlet__foot m-portlet__foot--fit">
                        <div class="m-form__actions">
                            <button type="submit" class="btn btn-primary">
                                Submit
                            </button>
                            <a href="{{ route('transactions.index') }}" class="btn btn-secondary">
                                Cancel
                            </a>
                        </div>
                    </div>
                </form>
                <!--end::Form-->
            </div>
        </div>
    </div>


@endsection
@section('scripts')
    <script src="{{ asset('theme/js/bootstrap-daterangepicker.js') }}" type="text/javascript"></script>
    <script src="{{ asset('theme/js/bootstrap-select.js') }}" type="text/javascript"></script>

    <script>
        $(document).ready(function () {

            $.validator.setDefaults({
                debug: true,
                success: "valid"
            });
            $('#transactionForm').validate({
                ignore: "input[type='text']:hidden",
                rules: {
                    user_id: "required",
                    amount: {
                        required: true,
                        number: true
                    },
                    with_interest:'required',
                    interest_rate: {
                        required: true,
                        number: true
                    },
                    dom_from:'required',
                    dom_to:'required',
                    payment_mode :'required',
                    note:'required'

                },
                messages: {
                    user_id: "Please select any Client",
                    amount: {required:"Amount field is required",number:"Only Numbers are allowed"},
                    with_interest: {
                        required: "With interest Field is required",
                    },
                    interest_rate :  {
                        required: 'Interest Rate required',
                        number:'Only Numbers are allowed'
                    },
                    date_from_to:'Select Date rage'
                },
                submitHandler: function (e) {
                    e.submit();
                }
            });

            $( ".interestOption" ).on( "click", function () {
                var interestOption = $(".interestOption:checked").val();
                if(interestOption == 'Yes') {
                    $('.IneterestDiv').show();
                    $('.IneterestDateDiv').show();
                    console.log("in");
                    $("#m_daterangepicker_2_validate").daterangepicker
                    ({buttonClasses:"m-btn btn",applyClass:"btn-primary",
                        cancelClass:"btn-secondary"},function(a,t,n)
                                    {
                                        console.log(a);
                                        $("#m_daterangepicker_3_validate .form-control").val(a.format("YYYY-MM-DD")+" / "+t.format("YYYY-MM-DD"))
                                    }
                                    )

                }
                else {
                    $('.IneterestDiv').hide();
                    $('.IneterestDateDiv').hide();
                }
            });
        });
    </script>
@endsection